"use client";

import { useEffect, useState } from "react";
import { RiQuestionLine } from "@remixicon/react";
import InfoPopover from "./info-popover";

export const CHUNK_EXPLANATION = "A chunk is a short piece of video and audio generated by FastH3. Chunks play one after another to form the continuous stream. This timer counts down to the next piece, not the next scheduled show.";

export default function ChunkCountdown({ chunkSeconds, startedAt }: { chunkSeconds: number; startedAt: number }) {
  const [now, setNow] = useState(0);

  useEffect(() => {
    const timer = window.setInterval(() => setNow(Date.now()), 250);
    return () => window.clearInterval(timer);
  }, []);

  const remaining = now
    ? Math.min(chunkSeconds * 1_000, Math.max(0, chunkSeconds * 1_000 - (now - startedAt)))
    : chunkSeconds * 1_000;
  const seconds = Math.ceil(remaining / 1_000);
  return (
    <div className="chunk-countdown">
      <span className="timer-copy"><span>Next chunk in</span><strong>{`00:${String(seconds).padStart(2, "0")}`}</strong></span>
      <InfoPopover title="What is a chunk?" trigger={<RiQuestionLine aria-hidden="true" />} triggerClassName="timer-help">
        <p>{CHUNK_EXPLANATION}</p>
      </InfoPopover>
    </div>
  );
}
